#!/usr/bin/env python3
"""
Builds the TRYKLI content from the level scripts in worlds/:

  - Assets/Resources/LevelDefinitions/level_XXX.json (100 levels) and worlds.json
  - Assets/Resources/Localization/fr.json and en.json (UI strings + level names, tips, custom objectives)
  - Tools/LevelAuthoring/REPORT.md (reference solution check with the approximate simulator)

Usage: python3 Tools/LevelAuthoring/build_levels.py [--no-search] [world numbers...]
After running it, open Unity and use Tools > TRYKLI > Generate Levels to refresh the LevelData assets, then
Tools > TRYKLI > Verify Level Solutions to confirm the solutions with the real Unity physics.
"""
import importlib
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, 'worlds'))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
LEVEL_DIR = os.path.join(ROOT, 'Assets', 'Resources', 'LevelDefinitions')
LOC_DIR = os.path.join(ROOT, 'Assets', 'Resources', 'Localization')

from finalize import finalize  # noqa: E402
from worlds_meta import WORLDS  # noqa: E402
import strings  # noqa: E402


def load_levels(world_ids):
    levels = []
    for world_id in world_ids:
        name = 'world%02d' % world_id
        if not os.path.exists(os.path.join(HERE, 'worlds', name + '.py')):
            print('missing', name)
            continue
        module = importlib.import_module(name)
        levels.extend(module.levels())
    return levels


def write_json(path, data):
    with open(path, 'w', encoding='utf-8') as handle:
        json.dump(data, handle, ensure_ascii=False, indent=1)
        handle.write('\n')


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    search = '--no-search' not in sys.argv
    import glob
    found = sorted(int(os.path.basename(f)[5:7]) for f in glob.glob(os.path.join(HERE, 'worlds', 'world[0-9][0-9].py')))
    world_ids = [int(a) for a in args] if args else found
    os.makedirs(LEVEL_DIR, exist_ok=True)
    os.makedirs(LOC_DIR, exist_ok=True)

    levels = load_levels(world_ids)
    rows = []
    texts = {}
    for level in levels:
        start = time.time()
        report = finalize(level, allow_search=search)
        definition = level.to_definition()
        write_json(os.path.join(LEVEL_DIR, 'level_%03d.json' % level.id), definition)
        texts['level.%03d.name' % level.id] = (level.name_fr, level.name_en)
        if level.tip_fr:
            texts['level.%03d.tip' % level.id] = (level.tip_fr, level.tip_en)
        texts.update(level.custom_texts)
        rows.append((level, report, time.time() - start))
        status = 'OK ' if report['success'] else 'FAIL'
        print('L%03d %s stars=%s t=%.1fs crystals=%s search=%s alt=%s' % (
            level.id, status, ''.join('*' if s else '.' for s in report['stars']), report['time'], report['crystals'],
            report['searched'], report['alternatives']))

    worlds = {'worlds': []}
    for w in WORLDS:
        worlds['worlds'].append({'worldId': w[0], 'nameKey': 'world.%d.name' % w[0], 'themeKey': 'world.%d.theme' % w[0],
                                 'mechanicKey': 'world.%d.mechanic' % w[0], 'backgroundTop': w[5], 'backgroundBottom': w[6],
                                 'blockColor': w[7], 'accentColor': w[8]})
        texts['world.%d.name' % w[0]] = (w[1], w[2])
        texts['world.%d.mechanic' % w[0]] = (w[3], w[4])
    write_json(os.path.join(LEVEL_DIR, 'worlds.json'), worlds)

    if not args:
        write_localization(texts)
        write_report(rows)


def write_localization(level_texts):
    for code, display, index in (('fr', 'Français', 0), ('en', 'English', 1)):
        entries = []
        for key, values in sorted(strings.UI.items()):
            entries.append({'key': key, 'value': values[index]})
        for key, values in sorted(level_texts.items()):
            entries.append({'key': key, 'value': values[index]})
        write_json(os.path.join(LOC_DIR, code + '.json'), {'code': code, 'displayName': display, 'entries': entries})


def write_report(rows):
    lines = ['# TRYKLI - level solution report', '',
             'Generated by `Tools/LevelAuthoring/build_levels.py` with the approximate Python simulator',
             '(`trykli_sim.py`, same gameplay rules and fixed step as the runtime, simplified Box2D contacts).',
             'Confirm in Unity with **Tools > TRYKLI > Verify Level Solutions** (real physics).', '',
             '| Level | Name | Difficulty | Solution | Stars (ref.) | Time (s) | Crystals | Winning combos / tried |',
             '|---|---|---|---|---|---|---|---|']
    ok = 0
    for level, report, _ in rows:
        ok += 1 if report['success'] else 0
        alt = report['alternatives']
        lines.append('| %03d | %s | %d | %s | %s | %.1f | %d/%d | %s |' % (
            level.id, level.name_fr, level.difficulty, 'OK' if report['success'] else 'FAIL (%s)' % report.get('failure'),
            ''.join('★' if s else '☆' for s in report['stars']), report['time'], report['crystals'][0], report['crystals'][1],
            '%d / %d' % alt if alt else '-'))
    lines.insert(6, '**%d / %d** reference solutions reach the exit in the simulator.' % (ok, len(rows)))
    lines.insert(7, '')
    with open(os.path.join(HERE, 'REPORT.md'), 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
