# -*- coding: utf-8 -*-
"""User interface strings (French / English). Level names, tips and level specific texts come from worlds/."""

UI = {
    # common
    "common.close": ("FERMER", "CLOSE"),
    "common.coming_soon": ("Bientôt disponible", "Coming soon"),
    "common.confirm": ("Confirmer ?", "Confirm?"),
    "common.no": ("NON", "NO"),
    "common.yes": ("OUI", "YES"),
    "common.on": ("ON", "ON"),
    "common.off": ("OFF", "OFF"),
    "error.no_levels": ("Aucun niveau trouvé.", "No level found."),
    "splash.studio": ("Un jeu de puzzle physique", "A physics puzzle game"),
    # main menu
    "menu.play": ("JOUER", "PLAY"),
    "menu.levels": ("NIVEAUX", "LEVELS"),
    "menu.settings": ("PARAMÈTRES", "SETTINGS"),
    "menu.skins": ("SKINS", "SKINS"),
    "menu.tagline": ("Observe. Place. Lance.", "Observe. Place. Launch."),
    "menu.progress": ("Étoiles {0} / {1}   ·   Cristaux {2}", "Stars {0} / {1}   ·   Crystals {2}"),
    # worlds / levels
    "worlds.title": ("MONDES", "WORLDS"),
    "worlds.total_stars": ("{0} / {1} étoiles", "{0} / {1} stars"),
    "worlds.card_title": ("MONDE {0} - {1}", "WORLD {0} - {1}"),
    "worlds.levels_done": ("{0} / {1} niveaux", "{0} / {1} levels"),
    "worlds.locked_message": ("Termine le monde précédent pour débloquer celui-ci.", "Finish the previous world to unlock this one."),
    "levels.boss": ("BOSS", "BOSS"),
    # HUD
    "hud.go": ("GO", "GO"),
    "hud.stop": ("STOP", "STOP"),
    "hud.level": ("{0}  {1}", "{0}  {1}"),
    "hud.trash": ("Lâche ici pour retirer", "Drop here to remove"),
    "hud.objectives_collapsed": ("Objectifs (toucher pour afficher)", "Objectives (tap to show)"),
    "hud.portal_count": ("{0} ({1})", "{0} ({1})"),
    # pause
    "pause.title": ("PAUSE", "PAUSE"),
    "pause.continue": ("CONTINUER", "CONTINUE"),
    "pause.restart": ("RECOMMENCER", "RESTART"),
    "pause.settings": ("PARAMÈTRES", "SETTINGS"),
    "pause.quit": ("QUITTER LE NIVEAU", "QUIT LEVEL"),
    # victory
    "victory.title": ("NIVEAU TERMINÉ", "LEVEL COMPLETE"),
    "victory.next": ("NIVEAU SUIVANT", "NEXT LEVEL"),
    "victory.replay": ("REJOUER", "REPLAY"),
    "victory.levels": ("NIVEAUX", "LEVELS"),
    "victory.stats": ("Temps {0} s   ·   Cristaux {1} / {2}", "Time {0} s   ·   Crystals {1} / {2}"),
    "victory.new_best": ("Nouveau record d'étoiles !", "New star record!"),
    "victory.world_unlocked": ("Monde {0} débloqué !", "World {0} unlocked!"),
    # failure
    "fail.msg.1": ("Oups.", "Oops."),
    "fail.msg.2": ("Presque.", "Almost."),
    "fail.msg.3": ("Trykli avait un autre plan.", "Trykli had another plan."),
    "fail.msg.4": ("Pas tout à fait.", "Not quite."),
    "fail.reason.hazard": ("Trykli a touché un danger.", "Trykli touched a hazard."),
    "fail.reason.out": ("Trykli est sorti du niveau.", "Trykli left the level."),
    "fail.reason.stuck": ("Trykli est coincé.", "Trykli is stuck."),
    "fail.reason.timeout": ("Temps maximum dépassé.", "Time limit exceeded."),
    "fail.reason.explosion": ("L'explosion était trop proche.", "The explosion was too close."),
    "fail.reason.unknown": ("Essaie encore.", "Try again."),
    "fail.retry": ("RÉESSAYER", "RETRY"),
    "fail.modify": ("MODIFIER", "MODIFY"),
    # hints
    "hint.button": ("INDICE", "HINT"),
    "hint.shown": ("Regarde la zone en surbrillance.", "Look at the highlighted zone."),
    "tip.generic": ("Observe bien le trajet de Trykli avant de placer.", "Watch Trykli's path carefully before placing."),
    "tip.item.spring": ("Essaie de modifier l'angle du ressort.", "Try changing the spring angle."),
    "tip.item.ramp": ("Une rampe change la direction de Trykli.", "A ramp changes Trykli's direction."),
    "tip.item.fan": ("La flèche du ventilateur montre la direction du vent.", "The fan arrow shows the wind direction."),
    "tip.item.portal_ab": ("Trykli sort du portail B dans la direction de sa flèche.", "Trykli leaves portal B the way its arrow points."),
    "tip.item.portal_cd": ("Les portails C/D forment une seconde paire.", "Portals C/D form a second pair."),
    "tip.item.magnet": ("L'aimant attire Trykli dans son cercle.", "The magnet pulls Trykli inside its circle."),
    "tip.item.bomb": ("L'explosion repousse Trykli loin de la bombe.", "The explosion pushes Trykli away from the bomb."),
    "tip.item.bumper": ("Le bumper renvoie Trykli à l'opposé du point de contact.", "The bumper sends Trykli away from the contact point."),
    "tip.item.mini_platform": ("Une petite plateforme peut servir d'appui.", "A small platform can be a stepping stone."),
    "tip.item.gravity_switch": ("L'inverseur retourne la gravité de Trykli.", "The switch flips Trykli's gravity."),
    # tutorial
    "tuto.drag": ("Glisse l'objet dans la zone en pointillés.", "Drag the object into the dotted zone."),
    "tuto.go": ("Appuie sur GO !", "Press GO!"),
    "tuto.rotate_intro": ("Place le ressort, puis tourne-le.", "Place the spring, then rotate it."),
    "tuto.rotate": ("Touche deux fois l'objet ou utilise les flèches pour le tourner.", "Double tap the object or use the arrows to rotate it."),
    "tuto.restart": ("RÉESSAYER relance le même plan. MODIFIER te laisse le changer.", "RETRY replays the same plan. MODIFY lets you change it."),
    # settings
    "settings.title": ("PARAMÈTRES", "SETTINGS"),
    "settings.music": ("Musique : {0}", "Music: {0}"),
    "settings.sounds": ("Sons : {0}", "Sounds: {0}"),
    "settings.vibrations": ("Vibrations : {0}", "Vibrations: {0}"),
    "settings.language": ("Langue : {0}", "Language: {0}"),
    "settings.credits": ("CRÉDITS", "CREDITS"),
    "settings.privacy": ("CONFIDENTIALITÉ", "PRIVACY"),
    "settings.reset": ("RÉINITIALISER", "RESET PROGRESS"),
    "settings.reset_confirm": ("Effacer toute la progression ?", "Erase all progress?"),
    "settings.reset_done": ("Progression réinitialisée.", "Progress reset."),
    "credits.title": ("CRÉDITS", "CREDITS"),
    "credits.body": ("TRYKLI\nConception et développement : l'équipe TRYKLI\nGraphismes et sons temporaires générés par le jeu.\nMerci d'avoir joué !",
                     "TRYKLI\nDesign and development: the TRYKLI team\nTemporary art and sounds generated by the game.\nThanks for playing!"),
    # skins
    "skins.title": ("SKINS", "SKINS"),
    "skins.crystals": ("Cristaux collectés : {0}", "Collected crystals: {0}"),
    "skins.selected": ("Choisi", "Selected"),
    "skins.available": ("Disponible", "Available"),
    "skins.cost": ("{0} cristaux", "{0} crystals"),
    "skin.classic": ("Classique", "Classic"),
    "skin.slime": ("Slime", "Slime"),
    "skin.ninja": ("Ninja", "Ninja"),
    "skin.robot": ("Robot", "Robot"),
    "skin.astronaut": ("Astronaute", "Astronaut"),
    "skin.pirate": ("Pirate", "Pirate"),
    # master
    "master.title": ("TRYKLI MASTER", "TRYKLI MASTER"),
    "master.button": ("TRYKLI MASTER", "TRYKLI MASTER"),
    "master.levels": ("Niveaux : {0}/{1}", "Levels: {0}/{1}"),
    "master.stars": ("Étoiles : {0}/{1}", "Stars: {0}/{1}"),
    "master.crystals": ("Cristaux : {0}/{1}", "Crystals: {0}/{1}"),
    "master.replay": ("REJOUER LES NIVEAUX", "REPLAY THE LEVELS"),
    "master.complete_stars": ("COMPLÉTER LES ÉTOILES", "COMPLETE THE STARS"),
    # items
    "item.spring": ("Ressort", "Spring"),
    "item.ramp": ("Rampe", "Ramp"),
    "item.fan": ("Ventilateur", "Fan"),
    "item.portal_ab": ("Portail A/B", "Portal A/B"),
    "item.portal_cd": ("Portail C/D", "Portal C/D"),
    "item.magnet": ("Aimant", "Magnet"),
    "item.bomb": ("Bombe", "Bomb"),
    "item.bumper": ("Bumper", "Bumper"),
    "item.mini_platform": ("Mini plateforme", "Mini platform"),
    "item.gravity_switch": ("Inverseur de gravité", "Gravity switch"),
    # objectives (generic descriptions)
    "obj.complete": ("Atteindre la sortie", "Reach the exit"),
    "obj.max_objects": ("Maximum {0} objets", "At most {0} objects"),
    "obj.max_objects_one": ("Utiliser 1 seul objet", "Use a single object"),
    "obj.items_any": ("objets", "objects"),
    "obj.only_item": ("Utiliser uniquement : {0}", "Use only: {0}"),
    "obj.use_item.atleast": ("Utiliser au moins {0} x {1}", "Use at least {0} x {1}"),
    "obj.use_item.atmost": ("Utiliser au plus {0} x {1}", "Use at most {0} x {1}"),
    "obj.use_item.exactly": ("Utiliser exactement {0} x {1}", "Use exactly {0} x {1}"),
    "obj.crystal_one": ("Récupérer le cristal", "Collect the crystal"),
    "obj.crystal_all": ("Récupérer tous les cristaux", "Collect every crystal"),
    "obj.crystals": ("Récupérer {0} cristaux", "Collect {0} crystals"),
    "obj.time": ("Terminer en moins de {0} s", "Finish in under {0} s"),
    "obj.bounce.atleast": ("Faire au moins {0} rebonds", "Make at least {0} bounces"),
    "obj.bounce.atmost": ("Faire au plus {0} rebonds", "Make at most {0} bounces"),
    "obj.bounce.exactly": ("Faire exactement {0} rebonds", "Make exactly {0} bounces"),
    "obj.bumper.atleast": ("Toucher au moins {0} bumpers", "Hit at least {0} bumpers"),
    "obj.bumper.atmost": ("Toucher au plus {0} bumpers", "Hit at most {0} bumpers"),
    "obj.bumper.exactly": ("Exactement {0} contacts bumper", "Exactly {0} bumper hits"),
    "obj.no_hazard.any": ("Ne toucher aucun danger", "Touch no hazard"),
    "obj.no_hazard.spikes": ("Ne toucher aucun pic", "Touch no spikes"),
    "obj.no_hazard.laser": ("Aucun contact laser", "No laser contact"),
    "obj.no_hazard.explosion": ("Rester loin des explosions", "Stay away from explosions"),
    "obj.avoid.ground": ("Ne pas toucher le sol", "Do not touch the ground"),
    "obj.avoid.wall": ("Ne toucher aucun mur", "Never touch a wall"),
    "obj.avoid.ceiling": ("Ne pas toucher le plafond", "Do not touch the ceiling"),
    "obj.avoid.obstacle": ("Aucun contact avec un obstacle", "No contact with an obstacle"),
    "obj.avoid.platform": ("Ne toucher aucune plateforme", "Touch no platform"),
    "obj.attempts": ("Réussir en {0} essais maximum", "Succeed within {0} tries"),
    "obj.first_try": ("Réussir du premier coup", "Succeed on the first try"),
    "obj.no_stop": ("Ne jamais s'arrêter", "Never stop"),
    "obj.interaction.button.atleast": ("Activer {0} bouton(s)", "Press {0} button(s)"),
    "obj.interaction.button.atmost": ("Activer au plus {0} bouton(s)", "Press at most {0} button(s)"),
    "obj.interaction.button.exactly": ("Activer exactement {0} bouton(s)", "Press exactly {0} button(s)"),
    "obj.interaction.portal.atleast": ("Utiliser les portails {0} fois", "Use portals {0} times"),
    "obj.interaction.portal.atmost": ("Utiliser les portails au plus {0} fois", "Use portals at most {0} times"),
    "obj.interaction.portal.exactly": ("Utiliser les portails exactement {0} fois", "Use portals exactly {0} times"),
    "obj.interaction.explosion.atleast": ("Déclencher {0} explosion(s)", "Trigger {0} explosion(s)"),
    "obj.interaction.explosion.atmost": ("Au plus {0} explosion(s)", "At most {0} explosion(s)"),
    "obj.interaction.explosion.exactly": ("Exactement {0} explosion(s)", "Exactly {0} explosion(s)"),
    "obj.interaction.gravity_flip.atleast": ("Inverser la gravité {0} fois", "Flip gravity {0} times"),
    "obj.interaction.gravity_flip.atmost": ("Au plus {0} inversion(s)", "At most {0} flip(s)"),
    "obj.interaction.gravity_flip.exactly": ("Exactement {0} inversion(s)", "Exactly {0} flip(s)"),
    "obj.interaction.door_open.atleast": ("Ouvrir {0} porte(s)", "Open {0} door(s)"),
    "obj.interaction.door_open.atmost": ("Ouvrir au plus {0} porte(s)", "Open at most {0} door(s)"),
    "obj.interaction.door_open.exactly": ("Ouvrir exactement {0} porte(s)", "Open exactly {0} door(s)"),
    "obj.interaction.laser_off.atleast": ("Désactiver {0} laser(s)", "Disable {0} laser(s)"),
    "obj.interaction.laser_off.atmost": ("Désactiver au plus {0} laser(s)", "Disable at most {0} laser(s)"),
    "obj.interaction.laser_off.exactly": ("Désactiver exactement {0} laser(s)", "Disable exactly {0} laser(s)"),
    "obj.interaction.zone.atleast": ("Passer par la zone indiquée", "Go through the marked zone"),
    "obj.interaction.zone.atmost": ("Éviter la zone indiquée", "Avoid the marked zone"),
    "obj.interaction.zone.exactly": ("Passer par la zone indiquée", "Go through the marked zone"),
    "obj.interaction.cannon.atleast": ("Utiliser le canon", "Use the cannon"),
    "obj.interaction.cannon.atmost": ("Éviter le canon", "Avoid the cannon"),
    "obj.interaction.cannon.exactly": ("Utiliser le canon {0} fois", "Use the cannon {0} times"),
}
