using System;
using System.Collections.Generic;
using Trykli.Data;
using Trykli.Mechanics;
using UnityEngine;

namespace Trykli.Gameplay
{
    /// <summary>Default <see cref="ElementData"/> per type (used by the Level Editor and for placed items).</summary>
    public static class ElementDefaults
    {
        public static ElementData Create(ElementType type)
        {
            var data = new ElementData { type = type };
            switch (type)
            {
                case ElementType.Block:
                    data.size = new Vector2(2f, 0.5f);
                    break;
                case ElementType.Spikes:
                    data.size = new Vector2(1f, 0.4f);
                    break;
                case ElementType.Bomb:
                    data.lethal = false;
                    break;
                case ElementType.Door:
                    data.activation = ActivationMode.ActivatedBySignal;
                    data.channel = 0;
                    break;
                case ElementType.Button:
                    data.emitChannel = 0;
                    break;
                case ElementType.Portal:
                    data.channel = 2;
                    data.endpoint = "A";
                    break;
                case ElementType.GravitySwitch:
                    data.oneShot = false;
                    break;
                case ElementType.MovingPlatform:
                    data.travel = new Vector2(3f, 0f);
                    data.period = 4f;
                    break;
                case ElementType.StickyZone:
                case ElementType.Marker:
                    data.size = new Vector2(2f, 1f);
                    break;
                case ElementType.SlipperyZone:
                    data.size = new Vector2(3f, 0.4f);
                    break;
            }

            return data;
        }
    }

    /// <summary>
    /// Creates level elements from layout data. Uses the prefab registered in <see cref="ElementPrefabCatalog"/>
    /// when available (generated by Tools > TRYKLI > Setup Project), otherwise builds the object procedurally.
    /// </summary>
    public static class ElementFactory
    {
        private static readonly Dictionary<ElementType, Type> ComponentTypes = new Dictionary<ElementType, Type>
        {
            { ElementType.Block, typeof(StaticBlock) },
            { ElementType.Spikes, typeof(HazardSpikes) },
            { ElementType.Crystal, typeof(Crystal) },
            { ElementType.Spring, typeof(Spring) },
            { ElementType.Ramp, typeof(Ramp) },
            { ElementType.MiniPlatform, typeof(Ramp) },
            { ElementType.Fan, typeof(Fan) },
            { ElementType.Portal, typeof(Portal) },
            { ElementType.Magnet, typeof(Magnet) },
            { ElementType.Bomb, typeof(Bomb) },
            { ElementType.Bumper, typeof(Bumper) },
            { ElementType.MovingPlatform, typeof(MovingPlatform) },
            { ElementType.RotatingPlatform, typeof(RotatingPlatform) },
            { ElementType.Button, typeof(ButtonTrigger) },
            { ElementType.Door, typeof(Door) },
            { ElementType.Laser, typeof(Laser) },
            { ElementType.GravitySwitch, typeof(GravitySwitch) },
            { ElementType.StickyZone, typeof(StickyZone) },
            { ElementType.SlipperyZone, typeof(SlipperyZone) },
            { ElementType.Cannon, typeof(Cannon) },
            { ElementType.Marker, typeof(MarkerZone) }
        };

        public static Type ComponentTypeFor(ElementType type)
        {
            return ComponentTypes.TryGetValue(type, out Type componentType) ? componentType : typeof(StaticBlock);
        }

        public static GameObject Create(ElementData data, Transform parent, WorldTheme theme, bool allowPrefab = true)
        {
            GameObject prefab = allowPrefab ? ElementPrefabCatalog.GetPrefab(data.type) : null;
            GameObject go;
            if (prefab != null)
            {
                go = UnityEngine.Object.Instantiate(prefab, parent);
            }
            else
            {
                go = CreateBare(data.type);
                go.transform.SetParent(parent, false);
            }

            go.name = string.IsNullOrEmpty(data.id) ? data.type.ToString() : $"{data.type}_{data.id}";
            go.transform.position = data.position;
            go.transform.rotation = Quaternion.Euler(0f, 0f, data.rotation);
            foreach (IConfigurableElement element in go.GetComponents<IConfigurableElement>()) element.Configure(data, theme);
            return go;
        }

        /// <summary>Creates an empty GameObject with the component matching the element type.</summary>
        public static GameObject CreateBare(ElementType type)
        {
            var go = new GameObject(type.ToString());
            go.AddComponent(ComponentTypeFor(type));
            return go;
        }

        public static ElementType TypeForItem(ItemKind kind)
        {
            switch (kind)
            {
                case ItemKind.Spring: return ElementType.Spring;
                case ItemKind.Ramp: return ElementType.Ramp;
                case ItemKind.Fan: return ElementType.Fan;
                case ItemKind.Portal: return ElementType.Portal;
                case ItemKind.Magnet: return ElementType.Magnet;
                case ItemKind.Bomb: return ElementType.Bomb;
                case ItemKind.Bumper: return ElementType.Bumper;
                case ItemKind.MiniPlatform: return ElementType.MiniPlatform;
                case ItemKind.GravitySwitch: return ElementType.GravitySwitch;
                default: return ElementType.Block;
            }
        }

        /// <summary>Layout data describing an item placed by the player.</summary>
        public static ElementData DataForItem(ItemDefinition item, Vector2 position, float rotation, string endpoint)
        {
            ElementData data = ElementDefaults.Create(TypeForItem(item.kind));
            data.id = "placed_" + item.itemId;
            data.position = position;
            data.rotation = rotation;
            data.power = item.power;
            data.surface = SurfaceKind.Platform;
            if (item.kind == ItemKind.Portal)
            {
                data.channel = Mathf.Max(0, item.portalChannel);
                data.endpoint = string.IsNullOrEmpty(endpoint) ? "A" : endpoint;
            }
            else
            {
                data.channel = -1;
            }

            return data;
        }
    }

}
