using System;
using System.Collections.Generic;
using UnityEngine;

namespace Trykli.Utilities
{
    /// <summary>
    /// Optional asset mapping <see cref="ArtId"/> values to real sprites.
    /// Generated by "Tools > TRYKLI > Setup Project" with baked placeholder PNGs; replace any sprite
    /// in this asset to swap the art without modifying code.
    /// </summary>
    [CreateAssetMenu(menuName = "TRYKLI/Sprite Library", fileName = "TrykliSpriteLibrary")]
    public sealed class SpriteLibrary : ScriptableObject
    {
        public const string ResourcePath = "TrykliSpriteLibrary";

        [Serializable]
        public struct Entry
        {
            public ArtId id;
            public Sprite sprite;
        }

        [SerializeField] private List<Entry> entries = new List<Entry>();

        private Dictionary<ArtId, Sprite> _lookup;

        public IReadOnlyList<Entry> Entries => entries;

        public bool TryGet(ArtId id, out Sprite sprite)
        {
            if (_lookup == null)
            {
                _lookup = new Dictionary<ArtId, Sprite>();
                foreach (Entry entry in entries)
                {
                    if (entry.sprite != null) _lookup[entry.id] = entry.sprite;
                }
            }

            return _lookup.TryGetValue(id, out sprite);
        }

        public void SetEntries(List<Entry> newEntries)
        {
            entries = newEntries ?? new List<Entry>();
            _lookup = null;
        }
    }
}
