using System.Collections.Generic;
using UnityEngine;

namespace Trykli.Data
{
    /// <summary>
    /// Registry of every world and level. Loaded from Resources/TrykliLevelDatabase (generated by
    /// "Tools > TRYKLI > Generate Levels"). If the asset does not exist yet, the database is built in memory
    /// from the JSON level definitions so the game is always playable.
    /// </summary>
    [CreateAssetMenu(menuName = "TRYKLI/Level Database", fileName = "TrykliLevelDatabase")]
    public sealed class LevelDatabase : ScriptableObject
    {
        public const string ResourcePath = "TrykliLevelDatabase";
        public const string DefinitionsFolder = "LevelDefinitions";
        public const string WorldsResource = "LevelDefinitions/worlds";

        [SerializeField] private ItemCatalog itemCatalog;
        [SerializeField] private List<WorldData> worlds = new List<WorldData>();
        [SerializeField] private List<LevelData> levels = new List<LevelData>();

        private Dictionary<int, LevelData> _levelLookup;
        private Dictionary<int, WorldData> _worldLookup;

        public ItemCatalog Items
        {
            get
            {
                if (itemCatalog == null) itemCatalog = ItemCatalog.CreateDefault();
                return itemCatalog;
            }
        }

        public IReadOnlyList<WorldData> Worlds => worlds;
        public IReadOnlyList<LevelData> Levels => levels;
        public int LevelCount => levels.Count;
        public int WorldCount => worlds.Count;

        public int LevelsPerWorld
        {
            get
            {
                int max = 0;
                foreach (WorldData world in worlds) max = Mathf.Max(max, world.levels.Count);
                return max > 0 ? max : 10;
            }
        }

        public bool IsBuiltFromJson { get; private set; }

        public void SetContent(ItemCatalog catalog, List<WorldData> newWorlds, List<LevelData> newLevels)
        {
            itemCatalog = catalog;
            worlds = newWorlds ?? new List<WorldData>();
            levels = newLevels ?? new List<LevelData>();
            worlds.Sort((a, b) => a.worldId.CompareTo(b.worldId));
            levels.Sort((a, b) => a.levelId.CompareTo(b.levelId));
            _levelLookup = null;
            _worldLookup = null;
        }

        public LevelData GetLevel(int levelId)
        {
            EnsureLookups();
            return _levelLookup.TryGetValue(levelId, out LevelData level) ? level : null;
        }

        public WorldData GetWorld(int worldId)
        {
            EnsureLookups();
            return _worldLookup.TryGetValue(worldId, out WorldData world) ? world : null;
        }

        public List<LevelData> GetLevelsOfWorld(int worldId)
        {
            var list = new List<LevelData>();
            foreach (LevelData level in levels)
            {
                if (level != null && level.worldId == worldId) list.Add(level);
            }

            list.Sort((a, b) => a.levelNumber.CompareTo(b.levelNumber));
            return list;
        }

        /// <summary>Level following <paramref name="levelId"/>, or -1 for the last level.</summary>
        public int GetNextLevelId(int levelId)
        {
            foreach (LevelData level in levels)
            {
                if (level != null && level.levelId > levelId) return level.levelId;
            }

            return -1;
        }

        public int FirstLevelIdOfWorld(int worldId)
        {
            List<LevelData> worldLevels = GetLevelsOfWorld(worldId);
            return worldLevels.Count > 0 ? worldLevels[0].levelId : -1;
        }

        private void EnsureLookups()
        {
            if (_levelLookup != null) return;
            _levelLookup = new Dictionary<int, LevelData>();
            _worldLookup = new Dictionary<int, WorldData>();
            foreach (LevelData level in levels)
            {
                if (level != null) _levelLookup[level.levelId] = level;
            }

            foreach (WorldData world in worlds)
            {
                if (world != null) _worldLookup[world.worldId] = world;
            }
        }

        public static LevelDatabase Load()
        {
            LevelDatabase database = Resources.Load<LevelDatabase>(ResourcePath);
            if (database != null && database.LevelCount > 0) return database;
            return BuildFromDefinitions();
        }

        /// <summary>Builds an in-memory database from the JSON files in Resources/LevelDefinitions.</summary>
        public static LevelDatabase BuildFromDefinitions()
        {
            ItemCatalog catalog = ItemCatalog.CreateDefault();
            var definitions = new List<LevelDefinition>();
            foreach (TextAsset asset in Resources.LoadAll<TextAsset>(DefinitionsFolder))
            {
                if (asset.name == "worlds") continue;
                LevelDefinition definition = LevelDefinitionConverter.ParseLevel(asset.text);
                if (definition != null && definition.levelId > 0) definitions.Add(definition);
            }

            TextAsset worldsAsset = Resources.Load<TextAsset>(WorldsResource);
            WorldCollectionDefinition worldDefinitions = LevelDefinitionConverter.ParseWorlds(worldsAsset != null ? worldsAsset.text : null);
            return Build(catalog, worldDefinitions.worlds, definitions);
        }

        public static LevelDatabase Build(ItemCatalog catalog, List<WorldDefinition> worldDefinitions, List<LevelDefinition> levelDefinitions)
        {
            var database = CreateInstance<LevelDatabase>();
            database.name = "LevelDatabase (runtime)";
            database.IsBuiltFromJson = true;

            var worldLookup = new Dictionary<int, WorldData>();
            var worldList = new List<WorldData>();
            foreach (WorldDefinition definition in worldDefinitions)
            {
                var world = CreateInstance<WorldData>();
                LevelDefinitionConverter.Apply(definition, world);
                world.name = $"World_{definition.worldId:00}";
                worldLookup[world.worldId] = world;
                worldList.Add(world);
            }

            var levelList = new List<LevelData>();
            foreach (LevelDefinition definition in levelDefinitions)
            {
                var level = CreateInstance<LevelData>();
                level.name = $"Level_{definition.levelId:000}";
                LevelDefinitionConverter.Apply(definition, level, catalog);
                levelList.Add(level);

                if (!worldLookup.TryGetValue(level.worldId, out WorldData world))
                {
                    world = CreateInstance<WorldData>();
                    world.worldId = level.worldId;
                    world.displayNameKey = $"world.{level.worldId}.name";
                    world.name = $"World_{level.worldId:00}";
                    worldLookup[world.worldId] = world;
                    worldList.Add(world);
                }

                world.levels.Add(level);
            }

            foreach (WorldData world in worldList) world.levels.Sort((a, b) => a.levelNumber.CompareTo(b.levelNumber));
            database.SetContent(catalog, worldList, levelList);
            return database;
        }
    }
}
